server:
   port: 10120

spring:
   profiles:
      active: dev
   messages:
      basename: i18n/messages
      encoding: UTF-8
   application:
      name: redis-service

   redis:
      database: 0
      host: 127.0.0.1
      port: 6379
      password:
      timeout: 1000  # 连接超时时间（毫秒）



